DROP TABLE IF EXISTS horaire;
DROP TABLE IF EXISTS QS;
DROP TABLE IF EXISTS utilisateur;
DROP TABLE IF EXISTS donnesBancaire;
DROP TABLE IF EXISTS rayon;
DROP TABLE IF EXISTS employe;
DROP TABLE IF EXISTS uniteMesure;
DROP TABLE IF EXISTS pointRelais;
DROP TABLE IF EXISTS consommateur;
DROP TABLE IF EXISTS commande;
DROP TABLE IF EXISTS parcelle;
DROP TABLE IF EXISTS categorie;
DROP TABLE IF EXISTS horaireJour;
DROP TABLE IF EXISTS variete;
DROP TABLE IF EXISTS produit;
DROP TABLE IF EXISTS lot;
DROP TABLE IF EXISTS LDC;
DROP TABLE IF EXISTS Production;

source base_nw.sql